python create.py root="../../nature/class" out="../../test/class" template="template/common.html"
python create.py root="../../nature/bom" out="../../test/bom" template="template/common.html"
python create.py root="../../nature/util" out="../../test/util" template="template/common.html"
python create.py root="../../nature/type" out="../../test/type" template="template/common.html"
python create.py root="../../nature/html5" out="../../test/html5" template="template/common.html"
